<?php if($all->num_rows>=1):?>
<h3 id="title"><?=$user->nombre.''.$user->apellidos?> estas son tus tareas:</h3>
<ul class="todo">
    <?php while ($nota=$all->fetch_object()):?>
        <li><a href="<?=base_url?>nota/detail&id=<?=$nota->id?>">
            <?=($nota->estado=='done')?"<del>".substr($nota->titulo,0,30)."</del>..." : substr($nota->titulo,0,30)."..."?>
            </a>
            <a class="btn-todo" <?=($nota->estado=='done')? "href=''>✓ Realizado </a> " : "href='check&id=$nota->id'>✓ Check</a>" ?>
        </li>
    <?php endwhile;?>
    
</ul>
<?php elseif($notasToday->num_rows == 0):?>
    <br>
    <h3>Sin tareas para el dia de hoy, puede crear en la barra superior</h3>
<?php endif;?>