<h2 class="titleh2">Editar de ToDo</h2>
<div class="form">
    <form action="<?=base_url?>nota/update" method="post">
        <br>
        <label for="">Titulo</label><br>
        <input type="text" name="" value="<?=$nota->titulo?>"><br>

        <label for="">Descripcion</label><br>
        <textarea name="descripcion" cols="50" rows="10"><?=$nota->descripcion?></textarea><br>

        <label for="">Estado</label><br>
        <select name="estado">
            <option value="done" <?=$nota->estado=='done'? 'selected':'' ?> >Realizado</option>
            <option value="pending" <?=$nota->estado=='pending'? 'selected':'' ?>>Pendiente</option>
        </select><br>

        <label for="">Fecha</label><br>
        <input type="datetime" name="" value="<?=$nota->fecha?>"><br>

        <label for="">Hora</label><br>
        <input type="time" name="" value="<?=$nota->hora?>"><br>

        <input type="hidden" name="id" value="<?=$nota->id?>">
        <input type="submit" class="button" value="Actualizar">
    </form>
</div>