</section>
        <footer class="footer">
            <div class="information">
                <h4>Tienes 5 To Do </h4>
            </div>
            <div class="action">
                <a class="button" href="">Realizar todas</a>
                <a class="button" href="">Ver todas</a>
            </div>
            <div class="copy"><p>Realizado por Dann Higashi &COPY</p></div>
        </footer>
    </main>
</body>
</html>