<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>To Do app</title>
    <link rel="stylesheet" href="<?=base_url?>assets/styles.css">
</head>
<body>
    <main>
        <header class="header">
            <a class="logo" href="<?=base_url?>nota/index">ToDo App</a>
            <a class="user" href="<?=base_url?>usuario/myAccount">Mi Cuenta</a>
            <form action="<?=base_url?>nota/create" method="post">
                <input type="text" placeholder="<?=isset($_SESSION['user'])? "Añade tu nueva ToDo" : "Inicia sesion para añadir"?>" name="titulo" <?=isset($_SESSION['user'])?'' :'disabled'?>>
                <input type="submit" value="+" <?=isset($_SESSION['user'])?'' :'disabled'?>>
            </form>
            <div class="clear-fix"></div>
        </header>
        <section class="container">