<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>To Do app</title>
    <link rel="stylesheet" href="<?=base_url?>assets/styles.css">
</head>
<body>
    <main>
        <header class="header">
            <a class="logo" href="<?=base_url?>nota/index">ToDo App</a>
            <a class="user" href="<?=base_url?>usuario/myAccount">Mi Cuenta</a>
            <form action="<?=base_url?>usuario" method="post">
                <input type="text" placeholder="Añade tu nueva ToDo" name="titulo" disable>
                <input type="submit" value="+">
            </form>
        </header>
        <section class="container">