<div class="container-img">
    <img class="img-index" src="<?=base_url?>assets/img/todo.jpg" alt="Imagen promocional de todo">
</div>
<div class="index-title">
    <p>To Do APP</p>
    <h4></h4>
</div>
<div class="index-p">
    <p>To Do APP, es tu app que te ayuda a gestinar tus tareas del dia a dia y tener un control de tus metas.</p>
    <p>Comienza ahora, Registrate o inicia sesion</p>
    <p id="a-button"><a class="button" href="<?=base_url?>usuario/enter">Entrar</a></p>
</div>