<h3 id="titleR">Bienvenido a ToDo APP</h3>
<div class="form">
    <form action="<?=base_url?>usuario/create" method="POST">
    <?=isset($_SESSION['register']['create'])?'<p>'.$_SESSION['register']['create'].'</p>':''?>
        <h4>Registrate</h4>
        <hr>
        <label for="nombre">Nombre</label><br>
        <input type="text" name="nombre"><br>
        <?=Utils::showFlagFailed('register','nombre');?>

        <label for="apellidos">Apellidos</label><br>
        <input type="text" name="apellidos"><br>
        <?=Utils::showFlagFailed('register','apellidos');?>
        
        <label for="">Email</label><br>
        <input type="email" name="email"><br>
        <?=Utils::showFlagFailed('register','email');?>

        <label for="pass">Contraseña</label><br>
        <input type="password" name="pass"><br>
        <?=Utils::showFlagFailed('register','pass');?>

        <input type="submit" value="Enviar">
    </form>
    <?php Utils::deleteFlag('register');?>
</div><br>
<div class="form">
    <form action="" method="post">
        <h4>Inicia sesion</h4><hr>
        <label for="">Email</label><br>
        <input type="email" name="email"><br>

        <label for="pass">Contraseña</label><br>
        <input type="password" name="pass"><br>

        <input type="submit" value="Enviar">
    </form>
</div>