<h3 id="titleR">Bienvenido a ToDo APP</h3>
<h3 id=subtitleR>La APP donde gestionaras tus tareas y recordatorios diarios</h3>
<div class="form">
    <form action="" method="POST">
        <h4>Registrate</h4>
        <hr>
        <label for="nombre">Nombre</label><br>
        <input type="text" name="nombre"><br>

        <label for="apellidos">Apellidos</label><br>
        <input type="text" name="apellidos"><br>
        
        <label for="">Email</label><br>
        <input type="email" name="email"><br>

        <label for="pass">Contraseña</label><br>
        <input type="password" name="pass"><br>

        <input type="submit" value="Enviar">
    </form>
</div><br>
<div class="form">
    <form action="" method="post">
        <h4>Inicia sesion</h4><hr>
        <label for="">Email</label><br>
        <input type="email" name="email"><br>

        <label for="pass">Contraseña</label><br>
        <input type="password" name="pass"><br>

        <input type="submit" value="Enviar">
    </form>
</div>